# permissions for end users to edit bkapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkapp-editor-role
rules:
- apiGroups:
  - paas.bk.tencent.com
  resources:
  - bkapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.bk.tencent.com
  resources:
  - bkapps/status
  verbs:
  - get
