# permissions for end users to view bkapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkapp-viewer-role
rules:
- apiGroups:
  - paas.bk.tencent.com
  resources:
  - bkapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paas.bk.tencent.com
  resources:
  - bkapps/status
  verbs:
  - get
