# permissions for end users to edit domaingroupmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: domaingroupmapping-editor-role
rules:
- apiGroups:
  - paas.bk.tencent.com
  resources:
  - domaingroupmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.bk.tencent.com
  resources:
  - domaingroupmappings/status
  verbs:
  - get
