version: '3.2'
services:
  mysql_main:
    image: mysql:5.7.22
    volumes:
      - ${STORAGE_ROOT}/mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: bk_paas_ng
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3406:3306"
    command: [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
      ]
  minio:
    image: minio/minio:RELEASE.2018-08-02T23-11-36Z
    command: server /data
    volumes:
      - ${STORAGE_ROOT}/minio:/data
    ports:
      - "9100:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  redis_main:
    image: redis:3.2.0
    command: [
          "bash", "-c",
          '
           docker-entrypoint.sh
           --requirepass ${REDIS_PASSWORD}
          '
    ]
    volumes:
      - ${STORAGE_ROOT}/redis:/var/lib/redis
    ports:
      - "6479:6379"