version: '3.2'
services:
    mysql_main:
        image: mysql:5.7.22
        volumes:
            - ${STORAGE_ROOT}/mysql:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: bk_engine_ng
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
        ]
    minio:
        image: minio/minio:RELEASE.2018-08-02T23-11-36Z
        command: server /data
        volumes:
            - ${STORAGE_ROOT}/minio:/data
        environment:
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    redis_main:
        image: redis:3.2.0
        volumes:
            - ${STORAGE_ROOT}/redis:/var/lib/redis

networks:
  default:
    external:
      name: ${NETWORK_NAME}